server:
  port: 9092
  servlet:
    context-path: /storage

spring:
  application:
    name: plan-list-storage
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务发现，配置Nacos Server地址
        namespace: plan-list-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/plan_list_storage?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: fivefu

seata:
  tx-service-group: my_test_tx_group
  enabled: true
  registry:
    type: nacos
    nacos:
      application: plan-list-seata-server      #注册在nacos服务名
      server-addr: localhost:8848
      group: DEFAULT_GROUP
      namespace: plan-list-dev #注册在nacos命名空间