server:
  port: 9091
  servlet:
    context-path: /core
spring:
  application:
    name: plan-list-core
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务发现，配置Nacos Server地址
        namespace: plan-list-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/plan_list?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: fivefu
  data:
    mongodb:
      uri: mongodb://planlist:planlist@127.0.0.1:27017/plan_list
seata:
  tx-service-group: my_test_tx_group
  enabled: true
  registry:
    type: nacos
    nacos:
      application: plan-list-seata-server      #注册在nacos服务名
      server-addr: localhost:8848
      group: DEFAULT_GROUP
      namespace: plan-list-dev #注册在nacos命名空间

# 打开sentinel对feign的支持
feign:
  sentinel:
    enabled: false

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # 打印 mongodb 操作的具体语句。生产环境下，不建议开启。
