server:
  port: 9090

spring:
  application:
    name: plan-list-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务发现，配置Nacos Server地址
        namespace: plan-list-dev