server:
  port: 9090
  servlet:
    context-path: /user

spring:
  application:
    name: plan-list-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.103.4.235:3306/plan_list?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: text
    password: f4ux49
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.4.235:8848 # Nacos服务发现，配置Nacos Server地址
        namespace: plan-list-prd
    sentinel:
      transport:
        dashboard: 172.19.28.203:8080  # Sentinel 控制台
  redis:
    database: 0
    host: 47.103.4.235
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 2000
    password: pzw9d2u2
  # Spring Security 配置项，对应 SecurityProperties 配置类
  security:
    user:
      name: user
      password: user
      roles: ADMIN
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
# 打开 sentinel 对 feign 的支持
feign:
  sentinel:
    enabled: true

# jwt 的配置
jwt:
  tokenHeader: Authorization
  secret: bnt-secrt000001
  expiration: 604800 #秒 7天
  prefix: Bearer

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  mapper-locations: classpath:mapper/*.xml

# token配置
token:
  # 令牌有效期（默认30分钟）
  expireTime: 30
  secret: bnt-secrt
  header: Authorization

bnt:
  version: 1.0.0