server:
  port: 9010
spring:
  main:
    web-application-type: reactive
  application:
    name: plan-list-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: plan-list-dev
    gateway:
      routes:
        - id: plan-list-user   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://plan-list-user  #匹配后提供服务的路由地址,微服务名称方式来路由服务
          predicates:
            - Path=/user/**    #断言，路径相匹配的进行路由
        - id: plan-list-core
          uri: lb://plan-list-core
          predicates:
            - Path=/core/**
      discovery:
        locator:
          enabled: true # 开启通过服务中心的自动根据 serviceId 创建路由的功能